export const regions = [
  { value: 'Toshkent shahri', label: 'Toshkent shahri' },
  { value: 'Toshkent viloyati', label: 'Toshkent viloyati' },
  { value: 'Andijon viloyati', label: 'Andijon viloyati' },
  { value: 'Buxoro viloyati', label: 'Buxoro viloyati' },
  { value: 'Farg\'ona viloyati', label: 'Farg\'ona viloyati' },
  { value: 'Jizzax viloyati', label: 'Jizzax viloyati' },
  { value: 'Xorazm viloyati', label: 'Xorazm viloyati' },
  { value: 'Namangan viloyati', label: 'Namangan viloyati' },
  { value: 'Navoiy viloyati', label: 'Navoiy viloyati' },
  { value: 'Qashqadaryo viloyati', label: 'Qashqadaryo viloyati' },
  { value: 'Qoraqalpog\'iston Respublikasi', label: 'Qoraqalpog\'iston Respublikasi' },
  { value: 'Samarqand viloyati', label: 'Samarqand viloyati' },
  { value: 'Sirdaryo viloyati', label: 'Sirdaryo viloyati' },
  { value: 'Surxondaryo viloyati', label: 'Surxondaryo viloyati' }
];

export const districts: Record<string, string[]> = {
  'Toshkent shahri': [
    'Bektemir tumani',
    'Chilonzor tumani',
    'Hamza tumani',
    'Mirobod tumani',
    'Mirzo Ulug\'bek tumani',
    'Olmazor tumani',
    'Sergeli tumani',
    'Shayxontohur tumani',
    'Uchtepa tumani',
    'Yakkasaroy tumani',
    'Yunusobod tumani'
  ],
  'Toshkent viloyati': [
    'Angren shahri',
    'Bekobod shahri',
    'Chirchiq shahri',
    'Olmaliq shahri',
    'Ohangaron tumani',
    'Oqqo\'rg\'on tumani',
    'Bekobod tumani',
    'Bo\'stonliq tumani',
    'Bo\'ka tumani',
    'Qibray tumani',
    'Quyi Chirchiq tumani',
    'Parkent tumani',
    'Piskent tumani',
    'O\'rta Chirchiq tumani',
    'Chinoz tumani',
    'Yuqori Chirchiq tumani',
    'Zangiota tumani'
  ],
  'Andijon viloyati': [
    'Andijon shahri',
    'Andijon tumani',
    'Asaka tumani',
    'Baliqchi tumani',
    'Buloqboshi tumani',
    'Bo\'z tumani',
    'Jalaquduq tumani',
    'Izboskan tumani',
    'Qo\'rg\'ontepa tumani',
    'Marhamat tumani',
    'Oltinko\'l tumani',
    'Paxtaobod tumani',
    'Ulug\'nor tumani',
    'Xo\'jaobod tumani',
    'Shahrixon tumani'
  ],
  'Buxoro viloyati': [
    'Buxoro shahri',
    'Kogon shahri',
    'Buxoro tumani',
    'Vobkent tumani',
    'G\'ijduvon tumani',
    'Jondor tumani',
    'Kogon tumani',
    'Qorako\'l tumani',
    'Qorovulbozor tumani',
    'Olot tumani',
    'Peshku tumani',
    'Romitan tumani',
    'Shofirkon tumani'
  ],
  'Farg\'ona viloyati': [
    'Farg\'ona shahri',
    'Qo\'qon shahri',
    'Quva shahri',
    'Marg\'ilon shahri',
    'Beshariq tumani',
    'Bog\'dod tumani',
    'Buvayda tumani',
    'Dang\'ara tumani',
    'Yozyovon tumani',
    'Quva tumani',
    'Rishton tumani',
    'So\'x tumani',
    'Toshloq tumani',
    'O\'zbekiston tumani',
    'Uchko\'prik tumani',
    'Farg\'ona tumani',
    'Furqat tumani'
  ],
  'Jizzax viloyati': [
    'Jizzax shahri',
    'Arnasoy tumani',
    'Baxmal tumani',
    'G\'allaorol tumani',
    'Do\'stlik tumani',
    'Sharaf Rashidov tumani',
    'Zarbdor tumani',
    'Zafarobod tumani',
    'Zomin tumani',
    'Mirzacho\'l tumani',
    'Paxtakor tumani',
    'Yangiobod tumani'
  ],
  'Xorazm viloyati': [
    'Urganch shahri',
    'Xiva shahri',
    'Bog\'ot tumani',
    'Gurlan tumani',
    'Qo\'shko\'pir tumani',
    'Shovot tumani',
    'Urganch tumani',
    'Xazorasp tumani',
    'Xonqa tumani',
    'Xiva tumani',
    'Yangiariq tumani',
    'Yangibozor tumani'
  ],
  'Namangan viloyati': [
    'Namangan shahri',
    'Kosonsoy tumani',
    'Mingbuloq tumani',
    'Namangan tumani',
    'Norin tumani',
    'Pop tumani',
    'To\'raqo\'rg\'on tumani',
    'Uychi tumani',
    'Uchqo\'rg\'on tumani',
    'Chortoq tumani',
    'Chust tumani',
    'Yangiqo\'rg\'on tumani'
  ],
  'Navoiy viloyati': [
    'Navoiy shahri',
    'Zarafshon shahri',
    'Karmana tumani',
    'Konimex tumani',
    'Qiziltepa tumani',
    'Navbahor tumani',
    'Nurota tumani',
    'Tomdi tumani',
    'Uchquduq tumani',
    'Xatirchi tumani'
  ],
  'Qashqadaryo viloyati': [
    'Qarshi shahri',
    'Shahrisabz shahri',
    'G\'uzor tumani',
    'Dehqonobod tumani',
    'Qamashi tumani',
    'Qarshi tumani',
    'Koson tumani',
    'Kasbi tumani',
    'Kitob tumani',
    'Muborak tumani',
    'Nishon tumani',
    'Chiroqchi tumani',
    'Shahrisabz tumani',
    'Yakkabog\' tumani'
  ],
  'Qoraqalpog\'iston Respublikasi': [
    'Nukus shahri',
    'Amudaryo tumani',
    'Beruniy tumani',
    'Qorao\'zak tumani',
    'Kegeyli tumani',
    'Qo\'ng\'irot tumani',
    'Qanliko\'l tumani',
    'Mo\'ynoq tumani',
    'Nukus tumani',
    'Taxtako\'pir tumani',
    'To\'rtko\'l tumani',
    'Xo\'jayli tumani',
    'Chimboy tumani',
    'Shumanay tumani',
    'Ellikqala tumani'
  ],
  'Samarqand viloyati': [
    'Samarqand shahri',
    'Oqdaryo tumani',
    'Bulung\'ur tumani',
    'Jomboy tumani',
    'Ishtixon tumani',
    'Kattaqo\'rg\'on tumani',
    'Qo\'shrabot tumani',
    'Narpay tumani',
    'Nurabod tumani',
    'Payariq tumani',
    'Pastdarg\'om tumani',
    'Paxtachi tumani',
    'Samarqand tumani',
    'Toyloq tumani',
    'Urgut tumani'
  ],
  'Sirdaryo viloyati': [
    'Guliston shahri',
    'Shirin shahri',
    'Yangiyer shahri',
    'Boyovut tumani',
    'Guliston tumani',
    'Oqoltin tumani',
    'Sardoba tumani',
    'Sayxunobod tumani',
    'Sirdaryo tumani',
    'Xovos tumani'
  ],
  'Surxondaryo viloyati': [
    'Termiz shahri',
    'Angor tumani',
    'Boysun tumani',
    'Denov tumani',
    'Jarqo\'rg\'on tumani',
    'Qiziriq tumani',
    'Qumqo\'rg\'on tumani',
    'Muzrabot tumani',
    'Oltinsoy tumani',
    'Sariosiyo tumani',
    'Termiz tumani',
    'Uzun tumani',
    'Sherobod tumani',
    'Sho\'rchi tumani'
  ]
};

export const getDistricts = (regionValue: string) => {
  const list = districts[regionValue] || [];
  return list.map(d => ({ value: d, label: d }));
};
