export type Region = {
  value: string;
  label: string;
};

export type District = {
  value: string;
  label: string;
};

export const regions: Region[] = [
  { value: "toshkent", label: "Toshkent" },
  { value: "toshkent_viloyati", label: "Toshkent viloyati" },
  { value: "samarqand", label: "Samarqand" },
  { value: "buxoro", label: "Buxoro" },
  { value: "andijon", label: "Andijon" },
  { value: "fargona", label: "Farg'ona" },
  { value: "namangan", label: "Namangan" },
  { value: "qoraqalpogiston", label: "Qoraqalpog'iston" },
  { value: "xorazm", label: "Xorazm" },
  { value: "qashqadaryo", label: "Qashqadaryo" },
  { value: "surxondaryo", label: "Surxondaryo" },
  { value: "jizzax", label: "Jizzax" },
  { value: "sirdaryo", label: "Sirdaryo" },
  { value: "navoiy", label: "Navoiy" },
];

const districts: Record<string, District[]> = {
  "toshkent": [
    { value: "bektemir", label: "Bektemir tumani" },
    { value: "mirzo_ulugbek", label: "Mirzo Ulug'bek tumani" },
    { value: "mirobod", label: "Mirobod tumani" },
    { value: "olmazor", label: "Olmazor tumani" },
    { value: "sirghali", label: "Sirg'ali tumani" },
    { value: "uchtepa", label: "Uchtepa tumani" },
    { value: "shayxontohur", label: "Shayxontohur tumani" },
    { value: "yakkasaroy", label: "Yakkasaroy tumani" },
    { value: "yashnobod", label: "Yashnobod tumani" },
    { value: "yunusobod", label: "Yunusobod tumani" },
    { value: "chilonzor", label: "Chilonzor tumani" },
    { value: "yashnaobod", label: "Yashnaobod tumani" },
  ],
  "toshkent_viloyati": [
    { value: "bekobod", label: "Bekobod shahri" },
    { value: "olmaliq", label: "Olmaliq shahri" },
    { value: "angren", label: "Angren shahri" },
    { value: "chirchiq", label: "Chirchiq shahri" },
    { value: "ohangaron", label: "Ohangaron tumani" },
    { value: "bostonliq", label: "Bo'stonliq tumani" },
    { value: "qibray", label: "Qibray tumani" },
    { value: "parkent", label: "Parkent tumani" },
    { value: "piskent", label: "Piskent tumani" },
    { value: "quyi_chirchiq", label: "Quyi Chirchiq tumani" },
    { value: "yuqori_chirchiq", label: "Yuqori Chirchiq tumani" },
    { value: "zangiota", label: "Zangiota tumani" },
    { value: "toshkent", label: "Toshkent tumani" },
    { value: "urtachirchiq", label: "O'rtachirchiq tumani" },
  ],
  "namangan": [
    { value: "namangan_shahar", label: "Namangan shahri" },
    { value: "chust", label: "Chust tumani" },
    { value: "chortoq", label: "Chortoq tumani" },
    { value: "kosonsoy", label: "Kosonsoy tumani" },
    { value: "mingbuloq", label: "Mingbuloq tumani" },
    { value: "namangan_tumani", label: "Namangan tumani" },
    { value: "norin", label: "Norin tumani" },
    { value: "pop", label: "Pop tumani" },
    { value: "to'raqo'rg'on", label: "To'raqo'rg'on tumani" },
    { value: "uchqo'rg'on", label: "Uchqo'rg'on tumani" },
    { value: "uychi", label: "Uychi tumani" },
    { value: "yangiqo'rg'on", label: "Yangiqo'rg'on tumani" },
  ],
  "andijon": [
    { value: "andijon_shahar", label: "Andijon shahri" },
    { value: "asaka", label: "Asaka shahri" },
    { value: "xonobod", label: "Xonobod shahri" },
    { value: "andijon_tumani", label: "Andijon tumani" },
    { value: "baliqchi", label: "Baliqchi tumani" },
    { value: "bo'z", label: "Bo'z tumani" },
    { value: "buloqboshi", label: "Buloqboshi tumani" },
    { value: "izboskan", label: "Izboskan tumani" },
    { value: "jalaquduq", label: "Jalaquduq tumani" },
    { value: "marhamat", label: "Marhamat tumani" },
    { value: "oltinko'l", label: "Oltinko'l tumani" },
    { value: "paxtaobod", label: "Paxtaobod tumani" },
    { value: "qo'rg'ontepa", label: "Qo'rg'ontepa tumani" },
    { value: "shahrixon", label: "Shahrixon tumani" },
    { value: "ulug'nor", label: "Ulug'nor tumani" },
    { value: "xo'jaobod", label: "Xo'jaobod tumani" },
  ],
  "fargona": [
    { value: "fargona_shahar", label: "Farg'ona shahri" },
    { value: "margilan", label: "Marg'ilon shahri" },
    { value: "quvasoy", label: "Quvasoy shahri" },
    { value: "qo'qon", label: "Qo'qon shahri" },
    { value: "rishton", label: "Rishton shahri" },
    { value: "oltiariq", label: "Oltiariq tumani" },
    { value: "bag'dod", label: "Bag'dod tumani" },
    { value: "beshariq", label: "Beshariq tumani" },
    { value: "buvayda", label: "Buvayda tumani" },
    { value: "dang'ara", label: "Dang'ara tumani" },
    { value: "farg'ona_tumani", label: "Farg'ona tumani" },
    { value: "furqat", label: "Furqat tumani" },
    { value: "o'zbekiston", label: "O'zbekiston tumani" },
    { value: "qo'shtepa", label: "Qo'shtepa tumani" },
    { value: "rishton_tumani", label: "Rishton tumani" },
    { value: "so'x", label: "So'x tumani" },
    { value: "toshloq", label: "Toshloq tumani" },
    { value: "uchko'prik", label: "Uchko'prik tumani" },
    { value: "yozyovon", label: "Yozyovon tumani" },
  ],
  "samarqand": [
    { value: "samarqand_shahar", label: "Samarqand shahri" },
    { value: "urgut", label: "Urgut tumani" },
    { value: "bulungur", label: "Bulungur tumani" },
    { value: "ishtixon", label: "Ishtixon tumani" },
    { value: "jomboy", label: "Jomboy tumani" },
    { value: "kattaqo'rg'on", label: "Kattaqo'rg'on tumani" },
    { value: "narpay", label: "Narpay tumani" },
    { value: "nurobod", label: "Nurobod tumani" },
    { value: "oqdaryo", label: "Oqdaryo tumani" },
    { value: "paxtachi", label: "Paxtachi tumani" },
    { value: "payariq", label: "Payariq tumani" },
    { value: "pastdarg'om", label: "Pastdarg'om tumani" },
    { value: "samarqand_tumani", label: "Samarqand tumani" },
    { value: "toyloq", label: "Toyloq tumani" },
  ],
  "buxoro": [
    { value: "buxoro_shahar", label: "Buxoro shahri" },
    { value: "buxoro_tumani", label: "Buxoro tumani" },
    { value: "g'ijduvon", label: "G'ijduvon tumani" },
    { value: "jondor", label: "Jondor tumani" },
    { value: "kogon", label: "Kogon tumani" },
    { value: "olot", label: "Olot tumani" },
    { value: "peshku", label: "Peshku tumani" },
    { value: "qorako'l", label: "Qorako'l tumani" },
    { value: "qorovulbozor", label: "Qorovulbozor tumani" },
    { value: "romitan", label: "Romitan tumani" },
    { value: "shofirkon", label: "Shofirkon tumani" },
    { value: "vobkent", label: "Vobkent tumani" },
  ],
  "qoraqalpogiston": [
    { value: "nukus", label: "Nukus shahri" },
    { value: "amudaryo", label: "Amudaryo tumani" },
    { value: "beruniy", label: "Beruniy tumani" },
    { value: "bo'zatov", label: "Bo'zatov tumani" },
    { value: "ellikqal'a", label: "Ellikqal'a tumani" },
    { value: "kegeyli", label: "Kegeyli tumani" },
    { value: "mo'ynoq", label: "Mo'ynoq tumani" },
    { value: "nukus_tumani", label: "Nukus tumani" },
    { value: "qanliko'l", label: "Qanliko'l tumani" },
    { value: "qo'ng'irot", label: "Qo'ng'irot tumani" },
    { value: "shumanay", label: "Shumanay tumani" },
    { value: "taxtako'pir", label: "Taxtako'pir tumani" },
    { value: "to'rtko'l", label: "To'rtko'l tumani" },
    { value: "xo'jayli", label: "Xo'jayli tumani" },
    { value: "chimbay", label: "Chimbay tumani" },
  ],
  "xorazm": [
    { value: "urganch", label: "Urganch shahri" },
    { value: "xiva", label: "Xiva shahri" },
    { value: "bog'ot", label: "Bog'ot tumani" },
    { value: "gurlan", label: "Gurlan tumani" },
    { value: "qo'shko'pir", label: "Qo'shko'pir tumani" },
    { value: "urganch_tumani", label: "Urganch tumani" },
    { value: "xazorasp", label: "Xazorasp tumani" },
    { value: "xiva_tumani", label: "Xiva tumani" },
    { value: "yangiariq", label: "Yangiariq tumani" },
    { value: "yangibozor", label: "Yangibozor tumani" },
  ],
  "qashqadaryo": [
    { value: "qarshi", label: "Qarshi shahri" },
    { value: "shahrisabz", label: "Shahrisabz shahri" },
    { value: "chiroqchi", label: "Chiroqchi tumani" },
    { value: "dehqonobod", label: "Dehqonobod tumani" },
    { value: "g'uzor", label: "G'uzor tumani" },
    { value: "kamashi", label: "Kamashi tumani" },
    { value: "koson", label: "Koson tumani" },
    { value: "mirishkor", label: "Mirishkor tumani" },
    { value: "muborak", label: "Muborak tumani" },
    { value: "nishon", label: "Nishon tumani" },
    { value: "qarshi_tumani", label: "Qarshi tumani" },
    { value: "qitob", label: "Qitob tumani" },
    { value: "shahrisabz_tumani", label: "Shahrisabz tumani" },
    { value: "yakkabog'", label: "Yakkabog' tumani" },
  ],
  "surxondaryo": [
    { value: "termiz", label: "Termiz shahri" },
    { value: "angor", label: "Angor tumani" },
    { value: "bandixon", label: "Bandixon tumani" },
    { value: "boysun", label: "Boysun tumani" },
    { value: "denov", label: "Denov tumani" },
    { value: "jarqo'rg'on", label: "Jarqo'rg'on tumani" },
    { value: "qiziriq", label: "Qiziriq tumani" },
    { value: "qumqo'rg'on", label: "Qumqo'rg'on tumani" },
    { value: "muzrabot", label: "Muzrabot tumani" },
    { value: "oltinsoy", label: "Oltinsoy tumani" },
    { value: "sariosiyo", label: "Sariosiyo tumani" },
    { value: "sherobod", label: "Sherobod tumani" },
    { value: "sho'rchi", label: "Sho'rchi tumani" },
    { value: "termiz_tumani", label: "Termiz tumani" },
    { value: "uzun", label: "Uzun tumani" },
  ],
  "jizzax": [
    { value: "jizzax_shahar", label: "Jizzax shahri" },
    { value: "arnasoy", label: "Arnasoy tumani" },
    { value: "baxmal", label: "Baxmal tumani" },
    { value: "do'stlik", label: "Do'stlik tumani" },
    { value: "forish", label: "Forish tumani" },
    { value: "g'allaorol", label: "G'allaorol tumani" },
    { value: "jizzax_tumani", label: "Jizzax tumani" },
    { value: "mirzacho'l", label: "Mirzacho'l tumani" },
    { value: "paxtakor", label: "Paxtakor tumani" },
    { value: "yangiobod", label: "Yangiobod tumani" },
    { value: "zafarobod", label: "Zafarobod tumani" },
    { value: "zarbdor", label: "Zarbdor tumani" },
  ],
  "sirdaryo": [
    { value: "guliston", label: "Guliston shahri" },
    { value: "yangiyer", label: "Yangiyer shahri" },
    { value: "akaltyn", label: "Akaltyn tumani" },
    { value: "boyovut", label: "Boyovut tumani" },
    { value: "guliston_tumani", label: "Guliston tumani" },
    { value: "mirzaobod", label: "Mirzaobod tumani" },
    { value: "oqoltin", label: "Oqoltin tumani" },
    { value: "sardoba", label: "Sardoba tumani" },
    { value: "sayxunobod", label: "Sayxunobod tumani" },
    { value: "sirdaryo_tumani", label: "Sirdaryo tumani" },
    { value: "xavos", label: "Xavos tumani" },
  ],
  "navoiy": [
    { value: "navoiy_shahar", label: "Navoiy shahri" },
    { value: "zarafshon", label: "Zarafshon shahri" },
    { value: "karmana", label: "Karmana tumani" },
    { value: "konimex", label: "Konimex tumani" },
    { value: "navbahor", label: "Navbahor tumani" },
    { value: "navoiy_tumani", label: "Navoiy tumani" },
    { value: "nurota", label: "Nurota tumani" },
    { value: "qiziltepa", label: "Qiziltepa tumani" },
    { value: "tomdi", label: "Tomdi tumani" },
    { value: "uchquduq", label: "Uchquduq tumani" },
  ],
};

export const getDistricts = (regionValue: string): District[] => {
  return districts[regionValue] || [];
};
